version: "3.1"
services:
  contacts_go_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - go-contacts-testing
    depends_on:
      - contacts_mysql_test
    command: go test ./... -v -tags=${TAGS}
    environment:
      - CGO_ENABLED=0
  contacts_mysql_test:
    build:
      context: .
      dockerfile: tests/docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: testing
    ports:
      - 3307:3306
    networks:
      - go-contacts-testing
networks:
  go-contacts-testing:
    driver: bridge
