FROM golang:1.14-alpine

ENV GO111MODULE on

RUN apk update; \
    apk add --no-cache git; 

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

CMD CGO_ENABLED=0 go test ./... -v 